### ISSUE TITLE
Has this been tested with Mono and the Unity engine?

### ISSUE THREAD

**Issue by Veovis-Muaddib** [cdhowie/Eluant#1]
I'm considering using Lua for mod support in a game being written in Unity.  There are several available options for communication between C# and Lua, and some appear to not work on many/all Mono platforms.  I was wondering before I start installing this (And all the other options I'm trying out) if anyone else has tried it in Unity themselves, and on which platforms.

**Comment by cdhowie** [comment]
Personally, I have not as I don't use Unity.  I can say that this library depends on the native (C) Lua implementation, so if you can't use native libraries on your target platform then Eluant will not work for you.

**Comment by Veovis-Muaddib** [comment]
Ah, that does help, thanks.  That means it should work for Windows/OS X/Linux at the least, but likely not on any of the other possible platforms Unity supports.  That will likely be good enough for my own needs.

Thanks for the quick response, and for the project in general.  The fact that the project comes with tests and such a detailed readme is very impressive.

**Comment by cdhowie** [comment]
Note that iOS should be supported!  iOS does support native code execution, and there has been some work (partly by me and partly by another Eluant user) to get Eluant to work with Xamarin.iOS.

**Comment by Veovis-Muaddib** [comment]
Interesting, as an iOS port of what I'm working on is not yet on the table but may be in future.  Though Apple restrictions on downloading code mean that modding would only be possible on the local machine, or via copy and paste.  Still, that's better than nothing....

**Comment by charlenni** [comment]
We (WFoundation) use Eluant with Android (Xamarin.Android), iOS (Xamarin.iOS) and Windows Phone 7/8 (with KopiLua) and are very happy with it. Works perfect for us.
