### ISSUE TITLE
Is it possible/"easy" to sandbox the Lua machine?

### ISSUE THREAD

**Issue by Veovis-Muaddib** [cdhowie/Eluant#2]
I'm considering using Lua as a modding tool for a game I'm developing.  However I don't want to allow mods access to the hard drive, network, etc....

Basically I want to allow everything in Lua, save things that worry me such as file/network access.  Access control would be even better, where mods could request network access from the user on installation/configuration, but not required.

Additionally I want to only allow Lua access to C# functions that I manually add.

**Comment by cdhowie** [comment]
There is [general documentation on sandboxing Lua](http://lua-users.org/wiki/SandBoxes) on the Lua wiki.  I have written [a basic sandboxing script](https://gist.github.com/cdhowie/9176507) that I use in a production environment with untrusted code.  (You are free to use this script under the terms of Eluant's own license.  It will likely become part of Eluant at some future time.)

The sandbox script supports the following features:
- Proxied access to `print()`.  If you set the global `printproxy` to a function (including a CLR delegate wrapped as a function) that accepts a table, you can capture calls to `print()` and `io.write()` via this function and redirect the output somewhere else.  The sandbox script will set up all of the plumbing to make this happen.  (The global `printproxy` is reset back to `nil` by the sandbox script so it cannot be called directly by Lua code.)
- Uncatchable Lua errors.  If you raise an error (for example, by throwing a `LuaException` from the CLR or using the Lua `error()` function) that contains the string `$UNCATCHABLE$`, the Lua protected-call functions (`pcall()` and `xpcall()`) will be unable to catch this error.  This can be used to break out of misbehaving Lua code and return control to the point where Lua was invoked from the CLR side.  (CLR code can, of course, catch the `LuaException` and deal with it at any time.)

Here is an example print proxy configuration:

```
Action<LuaTable> proxy = (LuaTable t) => {
    var first = true;
    foreach (var i in t.EnumerateArray()) {
        if (!first) { Console.Write('\t'); }
        first = false;
        Console.Write(i.ToString());
    }
    Console.WriteLine();
};

using (var proxyFn = runtime.CreateFunctionFromDelegate(proxy)) {
    runtime.Globals["printproxy"] = proxyFn;
}

// Now run the sandbox script.
```

Note that the sandbox script assumes that there will be no _mutually_ untrusted code executed.  That is, the sandbox assumes that scripts run in the sandbox will not attempt to sabotage _each other_.  The host is guarded from scripts, but scripts are not guarded from other scripts.  If you do need to run mutually untrusted code, then you need to either:
1. Use multiple Lua runtimes, or
2. Disable access to the `raw*()`, `getmetatable()`, and `setmetatable()` functions by setting them to `nil`.  **This may break some scripts.**

**Comment by Veovis-Muaddib** [comment]
Thank you very much, this is exactly what I'm looking for!  Looks like access control is feasible with this information, and the depth of information available on the topic is quite handy.

It also appears that my question was not as directly related to Eluant/other lua environments as I first thought, and is more generally something to be handled in Lua.  That would explain why I had trouble finding the information on any individual environment.  Thanks for still pointing me in the right direction!

**Comment by cdhowie** [comment]
No problem.  Note that the general rule is: if you don't want Lua code to have access to something, set it to `nil` first.  Or, if you want to guard access, use this pattern:

```
do
    local real_foo = foo

    foo = function(...)
        -- Do tests on arguments

        return real_foo(...)
    end
end
```
